### ISSUE TITLE
Automatic Deployment Steps with Vercel, Staging

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/tiny-site-frontend#102]
### Automatic Deployment Steps with Vercel:

1. **Login to Vercel:**
   - Go to [Vercel Dashboard](https://vercel.com/dashboard) and log in to your Vercel account.

2. **Create a New Project:**
   - Click on the "Add" dropdown and select "Project."

3. **Import Repository:**
   - If your repository is not listed, click on "Missing Git repository?" and adjust GitHub App Permissions to add the repository to Vercel.

4. **Enter Project Name:**
   - Enter a name for your project.

5. **Framework Detection:**
   - Vercel will automatically detect the framework. If not, select "Next.js" as the framework.

6. **Deploy:**
   - Click the "Deploy" button.

7. **Automatic Framework Detection:**
   - If the framework is automatically detected, proceed to deployment.
   - If not, you may need to specify the build command using Yarn. Ensure your project is configured to build correctly with the following command:
     ```bash
     yarn build
     ```

8. **Monitor Deployment:**
   - Vercel will initiate the deployment process. Monitor the progress on the Vercel dashboard.

9. **Verify Deployment:**
   - Once the deployment is complete, visit the provided URL to verify that the application is live.

**Comment by vinit717** [comment]
Not relevant now
