### ISSUE TITLE
[PROD-DEPLOYMENT] Tiny Site Frontend 

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/tiny-site-frontend#115]
### Environmental variable
NEXT_PUBLIC_API_BASE_URL=https://services.realdevsquad.com/tinysite/v1
NEXT_PUBLIC_TINY_SITE=https://tinysite.realdevsquad.com

**Comment by ankushdharkar** [comment]
Site has been deployed to prod. https://tinysite.realdevsquad.com/
