### ISSUE TITLE
create login page for tiny site

### ISSUE THREAD

**Issue by gauravsinhaweb** [Real-Dev-Squad/tiny-site-frontend#16]
Prototype Design:

Username should not contain any special chars other than _, not even white space

![Screenshot 2023-09-29 001805](https://github.com/Real-Dev-Squad/tiny-site-frontend/assets/75125943/939fce63-1db3-4ea8-997b-0a53fb1d5e13)

Test cases:

- [ ] should have a username input box in the view
- [ ] should have a password input box in the view
- [ ] should have a login button

**Comment by iamitprakash** [comment]
Username should not contain any special chars other than _, not even white space
