### ISSUE TITLE
Sign-up page design doc

### ISSUE THREAD

**Issue by j24m** [Real-Dev-Squad/tiny-site-frontend#24]
## **Feature Overview :**

This document outlines the User interface design specifications for the signup page of our application. The primary goal is to create an aesthetically pleasing, user-friendly and intuitive signup page. 

### Header :

- Include the app logo
- Add a navigation link to login page for existing users.

### Registration form :

→ Include the following form fields : 

- Email
- Username
- Password
- Confirm password

→ Buttons :

- Include a signup button below the registration fields.
- Ensure proper button hover and click states.

### Footer :

- Include a basic footer.

### Design :
![image](https://github.com/Real-Dev-Squad/tiny-site-frontend/assets/53934353/2e89bcd4-4f86-40e9-86b3-d37eab329a1d)
**NOTE : Image that will be used will not have copyright issues.**

## Working Flow : 
**1. User Visits the Sign-Up Page :**
- The user navigates to the sign-up page,by clicking on a "Sign Up" or "Create Account" link or button.

**2. User Provides Information :**
- The user fills out the sign-up form.
- email(required) 
- Username(required)
- Password(required)
- Confirm password(required)

**3. Client-Side Validation :**
- As the user enters data, client-side validation checks are performed in real-time to ensure that the data is properly formatted and meets basic requirements. 
-> For example:
- Checking that the email address is in a valid format.
- Ensuring that required fields are not left blank.

**4. Submission of Data :**
- When the user completes the form and clicks the "Sign Up" or "Create Account" button, the data is submitted to the server for further processing.

**5. Server Side Validation :**
- (Info to be decided)

**6. Account Creation :**
- (Info to be decided)

**Comment by iamitprakash** [comment]
@j24m  can you provide me the source of image ..?
