### ISSUE TITLE
Unnecessary Re-renders for Unauthenticated Users

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/tiny-site-frontend#91]
**Description:**
We have identified a significant issue related to unnecessary re-renders within our application. The problem manifests when a user is not logged in and performs specific actions on the page. The actions triggering the re-renders include clicking anywhere on the page, clicking outside the main content area, and subsequently clicking anywhere on the page again.

**Steps to Reproduce:**
1. Open the application in an incognito window or log out if already logged in.
2. Navigate to any page within the application.
3. Click anywhere on the page.
4. Click outside the main content area.
5. Click anywhere on the page again.

**Expected Behavior:**
The application should not trigger unnecessary re-renders when the user is not logged in, and the described actions should not impact the rendering process.

**Actual Behavior:**
Unnecessary re-renders are occurring, causing potential performance issues and impacting the user experience.

**Comment by vinit717** [comment]
Not relevant as of now
